### ISSUE TITLE
Using existing official matlab image

### ISSUE THREAD

**Issue by vemonet** [mathworks-ref-arch/matlab-integration-for-jupyter#3]
The documentation https://github.com/mathworks-ref-arch/matlab-integration-for-jupyter/tree/main/matlab tell me to build matlab from scratch using the Dockerfile instructions available at https://github.com/mathworks-ref-arch/matlab-dockerfile

That said those instructions are way too long and require dozens of click click on shady web pages (it feels like closing all the advertisements on a badly coded web page)

But **we paid for Matlab licenses, and we now need to build it like a Lego...** For a paid product we expected to have better tools at our disposition. **Every other free platform for programmation are much easier to install and work with than Matlab**. Also we can't read matlab proprietary code, so we can't fix the thing MathWorks did wrong (a lot of things)

Normally I should not have to do anything else than providing my license file to an already built docker image.

So we have found this official Matlab image here: https://hub.docker.com/r/mathworks/matlab 

Which is finally user-friendly! We just need to pass the license file as an environment variable, but it relies on VNC, is not stable (surprising) and we get the black screen error regularly (cf. https://github.com/mathworks-ref-arch/matlab-integration-for-jupyter/issues/2). So this image cannot be used seriously.

**Is it possible to provide a clean image with matlab preinstalled on which we just need to install the jupyterlab-matlab-proxy (you could also install everything?)** (I remind you guys that clients are paying for Matlab, it's not free software, so it's outrageous to also ask them to build it)

Most solutions to run Matlab in the browser seems to be really unreliable (like VNC blacking out). Is there an actual stable solution to run matlab in the browser? Or is MathWorks still struggling to build web interface in 2021?

@prabhakk-mw

**Comment by prabhakk-mw** [comment]
Hi @vemonet 

Thank you for reaching out to us.

I apologize for the issues you are facing with our current offering.
We take your feedback seriously, and are working towards addressing all of them!

The docker containers on [Dockerhub](https://hub.docker.com/r/mathworks/matlab), is a good starting point for users. 

The github repository [matlab-dockerfile](https://github.com/mathworks-ref-arch/matlab-dockerfile) predates our containers on Dockerhub and will be updated to reflect the latest developments.

Coming to the issues at hand:
1. VNC Blackout issue: 
   I've updated [cf. #2](https://github.com/mathworks-ref-arch/matlab-integration-for-jupyter/issues/2) with a solution for it. Please let me know if that does resolve the issue.

2. Web access to containers much like the Jupyter integration is being worked on as we speak, and should be available for use shortly. 

3. We are also working on publishing a Container based on the [Dockerfile](https://github.com/mathworks-ref-arch/matlab-integration-for-jupyter/blob/main/matlab/Dockerfile) in this repository, so that MATLAB & its integration with Jupyter are all available in a single container.

Once again, thank you for your valuable feedback.
